controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    three_wheel_base_controller:
      type: three_wheel_controller/ThreeWheelSteeringController

joint_state_broadcaster:
  ros__parameters:
    {}

three_wheel_base_controller:
  ros__parameters:
    {}
