<?xml version="1.0"?>
<package format="3">
  <name>agv_map_3d</name>
  <version>0.1.0</version>
  <description>Export Cartographer 3D submaps and serve visualization assets.</description>
  <maintainer email="bwply2009@163.com">kisdy</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cartographer</depend>
  <exec_depend>python3</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
