controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.36
    wheel_radius: 0.09

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Jazzy: 用 .NAN 代替 has_*_limits 布尔值
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_deceleration: -1.0
    linear.x.max_acceleration_reverse: -1.0
    linear.x.max_deceleration_reverse: 1.0
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 2.0
    angular.z.max_deceleration: -2.0
    angular.z.max_acceleration_reverse: -2.0
    angular.z.max_deceleration_reverse: 2.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN


    publish_rate: 50.0
    publish_limited_velocity: true
    open_loop: true
    enable_odom_tf: false
    cmd_vel_timeout: 0.5